export * from "./About.common.tsx";
export * from "./BlogPage.common.tsx";
export * from "./ContactView.common.tsx";
export * from "./FooterView.common.tsx";
export * from "./HomeView.common.tsx";
export * from "./NavBarView.common.tsx";
export * from "./NotFound.common.tsx";
export * from "./PropetiesView.common.tsx";
export * from "./Registration.common.tsx"
export * from "./Login.common.tsx"